-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 01:12:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quicktalkdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quicktalkdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quicktalkdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quicktalkdb` ;

-- -----------------------------------------------------
-- Table `quicktalkdb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quicktalkdb`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(45) NULL DEFAULT NULL,
  `room_type` ENUM('single', 'group') NOT NULL DEFAULT 'single',
  `room_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quicktalkdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quicktalkdb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_Email_UNIQUE` (`user_email` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quicktalkdb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quicktalkdb`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `m_room_id` INT NOT NULL,
  `m_user_id` INT NOT NULL,
  `m_text` TEXT NOT NULL,
  `m_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`),
  INDEX `rm_room_id_idx` (`m_room_id` ASC) VISIBLE,
  INDEX `m_user_id_idx` (`m_user_id` ASC) VISIBLE,
  CONSTRAINT `m_room_id`
    FOREIGN KEY (`m_room_id`)
    REFERENCES `quicktalkdb`.`room` (`room_id`),
  CONSTRAINT `m_user_id`
    FOREIGN KEY (`m_user_id`)
    REFERENCES `quicktalkdb`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quicktalkdb`.`room_membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quicktalkdb`.`room_membership` (
  `room_membership_id` INT NOT NULL AUTO_INCREMENT,
  `rm_user_id` INT NOT NULL,
  `rm_room_id` INT NOT NULL,
  `rm_joined_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_membership_id`),
  INDEX `user_id_idx` (`rm_user_id` ASC) VISIBLE,
  INDEX `room_id_idx` (`rm_room_id` ASC) VISIBLE,
  CONSTRAINT `room_id`
    FOREIGN KEY (`rm_room_id`)
    REFERENCES `quicktalkdb`.`room` (`room_id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`rm_user_id`)
    REFERENCES `quicktalkdb`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;